cc=gcc
OBJECT=mysh.o,Fpipe.o,Fredirect.o,mypwd.o,mycat.o,myhead.o,mytail.o,mymkdir.o,myrm.o,myrmdir.o,myls.o,myp.o,set.o
MAIN_SOURCE=mysh.c
TARGET=mysh
${TARGET}:$(OBJECT)
	$(CC) -o $@ $(OBJECT) $(LFLAGS)

